name = "cf-mail"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "cf_mail_db"
database_id = ""

[[r2_buckets]]
binding = "R2"
bucket_name = "cf-mail-storage"

[assets]
directory = "public"
